# Generated by Django 4.2.3 on 2023-08-02 07:25

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, null=True, populate_from='name', unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('age', models.CharField(max_length=5, unique=True)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default=None, max_length=10)),
                ('religion', models.CharField(blank=True, choices=[('islam', 'Islam'), ('hinduism', 'Hinduism'), ('christian', 'Christian'), ('buddhism', 'Buddhism')], default=None, max_length=10)),
                ('image', models.ImageField(blank=True, default='default_user.png', null=True, upload_to='user/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
